### ISSUE TITLE
大神，请问c#怎么base64加密含有中文和符号的字符串？

### ISSUE THREAD

**Issue by WMdoit** [hyjiacan/Image2Base64#1]
在线等，急

**Comment by hyjiacan** [comment]
Convert.ToBase64String(data)

**Comment by WMdoit** [comment]
不行额,都试过了.这样转的和用软件转的不一样.
案例是下面这句(另外还有个问题,下面这句怎么定义为常量,因为含有等号,不会搞)
"(title="系统" && body="吃饭")&&country="CN"

**Comment by hyjiacan** [comment]
换编码试一下

**Comment by hyjiacan** [comment]
换编码试一下
